// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about_me: defineAsyncComponent(() => import("./AboutMe/index.vue")),
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue"),
  ),
  certificates: defineAsyncComponent(() => import("./Certificates/index.vue")),
  hero_section: defineAsyncComponent(() => import("./HeroSection/index.vue")),
  projects_section: defineAsyncComponent(
    () => import("./ProjectsSection/index.vue"),
  ),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  services_section: defineAsyncComponent(
    () => import("./ServicesSection/index.vue"),
  ),
  testimonials: defineAsyncComponent(() => import("./Testimonials/index.vue")),
});
